apiVersion: v1
kind: Secret
metadata:
  name: easyshop-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "easyshop.labels" . | nindent 4 }}
type: Opaque
data:
  NEXTAUTH_SECRET: {{ .Values.secrets.NEXTAUTH_SECRET | b64enc | quote }}
  JWT_SECRET:      {{ .Values.secrets.JWT_SECRET      | b64enc | quote }}