# Prod environment overrides
# GitHub Actions updates image.repository and image.tag on every merge to main

image:
  repository: "665908544590.dkr.ecr.ap-south-1.amazonaws.com/easyshop-prod"
  tag: "a61b21b5cd201cd06273f66b802d06010130ce4d"

replicaCount: 3

ingress:
  host: easyshop-siva.online    # ← replace with your domain or use nip.io
  certIssuer: letsencrypt-staging   # use staging issuer for prod to avoid hitting rate limits during testing; switch to letsencrypt-prod for production use

env:
  NEXT_PUBLIC_API_URL: "https://easyshop-siva.online/api"
  NEXTAUTH_URL: "https://easyshop-siva.online"

mongodb:
  storageSize: 20Gi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 65

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi

probes:
  liveness:
    path: /
    initialDelaySeconds: 30
    periodSeconds: 15
  readiness:
    path: /
    initialDelaySeconds: 15
    periodSeconds: 10