# Dev environment overrides
# GitHub Actions updates image.repository and image.tag on every push to develop

image:
  repository: "665908544590.dkr.ecr.ap-south-1.amazonaws.com/easyshop-dev"
  tag: "dev-0f7b3418ee86b2340c242cfe77b00d8a1e541d13"

replicaCount: 1

ingress:
  host: dev.easyshop-siva.online    # ← replace with your domain or use nip.io
  certIssuer: letsencrypt-staging   # use staging issuer for dev to avoid hitting rate limits during testing; switch to letsencrypt-prod for production use

env:
  NEXT_PUBLIC_API_URL: "https://dev.easyshop-siva.online/api"
  NEXTAUTH_URL: "https://dev.easyshop-siva.online"

mongodb:
  storageSize: 2Gi

autoscaling:
  enabled: false

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

probes:
  liveness:
    path: /
    initialDelaySeconds: 30
    periodSeconds: 15
  readiness:
    path: /
    initialDelaySeconds: 15
    periodSeconds: 10